//USER
export const LOGIN_USER = 'LOGIN_USER';
export const GET_ALL_STUDENTS = 'GET_ALL_STUDENTS';
export const GET_STUDENT = 'GET_STUDENT';
export const GET_ALL_TEACHERS = 'GET_ALL_TEACHERS';
export const GET_ALL_USERS = 'GET_ALL_USERS';